# Generated by Django 3.1.7 on 2021-04-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_reservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room_reservation',
            unique_together={('res_date', 'room')},
        ),
    ]
