# Generated by Django 3.1.7 on 2021-04-16 10:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210415_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_reservation',
            name='res_date',
            field=models.DateField(default=datetime.date(2021, 4, 16)),
        ),
        migrations.AlterField(
            model_name='room_reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.room'),
        ),
    ]
