# Generated by Django 3.1.7 on 2021-04-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210416_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='res_room', to='rooms.room'),
        ),
    ]
